### ISSUE TITLE
Ramadhan friendly message

### ISSUE THREAD

**Issue by aselhid** [rumah-kita-bersama/home-automation#1]
https://github.com/rumah-kita-bersama/home-automation/blob/248bdfdd260a3950d4e350bfa42266bf61d4d21a/doorbell_notifier/doorbell_notifier.ino#L49
Suggested new line
```
Assalamualaikum, ada orang di depan.
```

**Comment by fatanugraha** [comment]
Can raise MR to fix this? Much appreciated!

**Comment by aselhid** [comment]
> Can raise MR to fix this? Much appreciated!

yes bro, PR on #2 :)
